# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bC8UeWIhZfNe_2XHtIyGRXySrLG27fm
"""

!pip install -q streamlit

import streamlit as st
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/drive')

df_liner = pd.read_csv('/content/drive/MyDrive/liner_connectivity.csv')
df_liner.head()

st.title("Global Port Liner Connectivity Dashboard")
# Load data
@st.cache_data
def load_data():
  port_liner = pd.read_csv('/content/drive/MyDrive/port_liner.csv')
  df_liner = pd.read_csv('/content/drive/MyDrive/liner_connectivity.csv')
  return port_liner, df_liner
df_liner, port_liner = load_data()

df_liner['quarter_label'] = pd.to_datetime(df_liner['quarter_label'].str.replace(r'(Q\d) (\d+)', r'\2-\1'), errors='coerce')
port_liner['quarter_label'] = pd.to_datetime(port_liner['quarter_label'].str.replace(r'(Q\d) (\d+)', r'\2-\1'), errors='coerce')

# Sidebar filters
st.subheader('Raw data')
st.write(df_liner)