CREATE TABLE "ports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "country" varchar,
  "region" varchar
);

CREATE TABLE "quarters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "year" integer NOT NULL,
  "quarter" varchar NOT NULL
);

CREATE TABLE "connectivity_index" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "port_id" integer NOT NULL,
  "quarter_id" integer NOT NULL,
  "index_value" decimal(10,2) NOT NULL
);

COMMENT ON TABLE "quarters" IS 'Time label for the index';

COMMENT ON TABLE "connectivity_index" IS 'Index value of liner connectivity';

ALTER TABLE "connectivity_index" ADD FOREIGN KEY ("port_id") REFERENCES "ports" ("id");

ALTER TABLE "connectivity_index" ADD FOREIGN KEY ("quarter_id") REFERENCES "quarters" ("id");
